In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [9]:
d = np.zeros((2, 3))
print(d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
e = np.ones((3, 4))
print(e)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
np.full((2, 2), 7) 

array([[7, 7],
       [7, 7]])

In [14]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
np.arange(0, 5, 4)    # [0 2 4 6 8]

array([0, 4])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
a = np.array([1, 2, 3])
print(a.dtype)                 # int64

int32


In [26]:
b = np.array([1, 2, 3], dtype=np.float32)
print(b.dtype)                 # float32

float32


In [28]:
c = a.astype(np.float64) 
print(c)

[1. 2. 3.]


In [31]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)   # (2, 3) -> 2 rows, 3 columns
print(arr.ndim)    # 2      -> number of dimensions
print(arr.size)    # 6      -> total number of elements
print(arr.dtype)   # int64

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int32


In [33]:
a = np.arange(12)          # [0 1 2 ... 11]
print(a)
b = a.reshape(3, 4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
c = a.reshape(2, -1)
print(c)                   # -1 lets NumPy infer that dimension
print(c.shape)             # (2, 6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)


In [45]:
arr = np.array([[1, 2], [3, 4]])
print(arr)
print(arr.flatten())  # returns a copy
print(arr)
print(arr.ravel())     # returns a view when possible
print(arr)

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [46]:
l1 = [1, 2, 3, 4]
l2 = [4, 2, 3, 1]
print(l1)
print(l2)
print(l1+l2)

[1, 2, 3, 4]
[4, 2, 3, 1]
[1, 2, 3, 4, 4, 2, 3, 1]


In [47]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
 
print(a + b)   # Addition       -> [11 22 33 44]
print(a - b)   # Subtraction    -> [ 9 18 27 36]
print(a * b)   # Multiplication -> [10 40 90 160]
print(a / b)   # Division       -> [10. 10. 10. 10.]
print(a % b)   # Modulus        -> [0 0 0 0]
print(a ** 2)  # Exponent       -> [100 400 900 1600]

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[0 0 0 0]
[ 100  400  900 1600]


In [48]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print(a > b)     # [False False  True  True]
print(a == b)    # [False False False False]
print(a <= 2)    # [ True  True False False]

[False False  True  True]
[False False False False]
[ True  True False False]


In [54]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, 2))
print(np.mod(a, b))
print(np.abs(np.array([-1, -2, 3])))   # [1 2 3]

[5 5 5 5]
[-3 -1  1  3]
[4 6 6 4]
[0.25       0.66666667 1.5        4.        ]
[ 1  4  9 16]
[1 2 1 0]
[1 2 3]


In [55]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])     # 10 (first element)
print(a[3])     # 40 (fourth element)
 
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b[1, 2])  # 6  (row 1, column 2)

10
40
6


In [56]:
a = np.array([10, 20, 30, 40, 50])
print(a[-1])    # 50 (last element)
print(a[-2])    # 40 (second-to-last)

50
40


In [57]:
a = np.array([10, 20, 30, 40, 50])
print(a[1:4])    # [20 30 40]
print(a[:3])     # [10 20 30]
print(a[2:])     # [30 40 50]

[20 30 40]
[10 20 30]
[30 40 50]


In [58]:
a = np.arange(10)
print(a[::2])    # [0 2 4 6 8]   every 2nd element
print(a[1:8:2])  # [1 3 5 7]
print(a[::-1])   # reverse the array

[0 2 4 6 8]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [62]:
a = np.array([10, 20, 30, 40, 50, 60, 60, 30, 80])
idx = [0, 2, 7]
print(a[idx])    # [10 30 50]
print(type(idx))

[10 30 30]
<class 'list'>


In [66]:
a = np.array([10, 15, 20, 25, 30])
print(a)
mask = a > 18
print(mask)        # [False False  True  True  True]
print(a[mask])     # [20 25 30]
print(a[a % 10 == 0])   # [10 20 30]

[10 15 20 25 30]
[False False  True  True  True]
[20 25 30]
[10 20 30]


In [67]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [71]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a)
print(b)
print(np.concatenate([a, b]))    # [1 2 3 4 5 6]
print(np.vstack([a, b]))         # stack as rows -> shape (2,3)
print(np.hstack([a, b]))          # stack horizontally -> [1 2 3 4 5 6]
print(np.stack([a, b], axis=0))   # new axis -> shape (2,3)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [75]:
a = np.arange(9)
print(a)
np.split(a, 9)     # [array([0,1,2]), array([3,4,5]), array([6,7,8])]

[0 1 2 3 4 5 6 7 8]


[array([0]),
 array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([7]),
 array([8])]

In [77]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [82]:
b = np.append(a, [4, 5])       # [1 2 3 4 5]
print(a)
print(b)

[1 2 3]
[1 2 3 4 5]


In [80]:
print(np.insert(a, 1, 99))        # [1 99 2 3]
print(a)

[ 1 99  2  3]
[1 2 3]


In [84]:
c = np.delete(a, 0)            # [2 3]
print(a)
print(c)

[1 2 3]
[2 3]


In [85]:
a = np.array([3, 1, 4, 1, 5, 9, 2])
print(a)
b = np.sort(a)          # [1 1 2 3 4 5 9]
print(a)
print(b)

[3 1 4 1 5 9 2]
[3 1 4 1 5 9 2]
[1 1 2 3 4 5 9]


In [90]:
a = np.array([3, 1, 4, 1, 5, 9, 2])
print(a)
print(np.unique(a))         # [1 2 3 4 5 9]
print(a)
b = a[::-1]              # reverse -> [2 9 5 1 4 1 3]
print(a)
print(b)

[3 1 4 1 5 9 2]
[1 2 3 4 5 9]
[3 1 4 1 5 9 2]
[3 1 4 1 5 9 2]
[2 9 5 1 4 1 3]


In [92]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
print(matrix)
row_add = np.array([10, 20, 30])             # shape (3,)
print(row_add)
print(matrix + row_add)

[[1 2 3]
 [4 5 6]]
[10 20 30]
[[11 22 33]
 [14 25 36]]


In [3]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [10]:
rng = np.random.default_rng(seed=42)
rng1 = np.random.default_rng(42)

In [13]:
rng.integers(low=1, high=100, size=5)
rng1.integers(1, 50, size=(3,4))

array([[ 5, 38, 33, 22],
       [22, 43,  5, 35],
       [10,  5, 26, 48]], dtype=int64)

In [14]:
rng.normal(loc=0, scale=1, size=5)  

array([ 0.46750934, -0.85929246,  0.36875078, -0.9588826 ,  0.8784503 ])

In [15]:
rng.uniform(low=0, high=10, size=5)

array([6.31664399, 7.5808774 , 3.54525968, 9.70698024, 8.93121121])

In [21]:
rng = np.random.default_rng(seed=42)
print(rng.integers(0, 10, 3))

[0 7 6]


In [30]:
a = np.arange(10)
rng.shuffle(a)     # shuffles a in place
print(a)

[7 6 3 8 1 0 5 2 9 4]


In [41]:
options = np.array(['A', 'B', 'C', 'D'])
rng.choice(options, size=3, replace=False)

array(['A', 'D', 'B'], dtype='<U1')

In [1]:
import time
import numpy as np
 
size = 1_000_000
py_list = list(range(size))
np_array = np.arange(size)
 
start = time.time()
sum([x * 2 for x in py_list])
print('Python list:', time.time() - start, 'seconds')
 
start = time.time()
np_array * 2
print('NumPy array:', time.time() - start, 'seconds')

Python list: 0.10420775413513184 seconds
NumPy array: 0.01337122917175293 seconds
